# Generated by Django 4.2.5 on 2023-09-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
